---
- name: ping
  hosts: local_ubuntu
  become: true
  gather_facts: False
  
  tasks:
  - name: ping 
    ping:
  
  - name: ls root
    shell: ls /root
  
  - name: create file
    file:
      path: /root/test
      owner: administrator
      state: present
